---
- name: Install k3s on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - jq

    - name: Download k3s installation script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/install-k3s.sh
        mode: '0755'

    - name: Install k3s
      shell: /tmp/install-k3s.sh
      args:
        creates: /usr/local/bin/k3s
      register: k3s_install_result

    - name: Get k3s token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false
      when: k3s_install_result.changed

    - name: Display k3s token
      debug:
        var: k3s_token.stdout
      when: k3s_install_result.changed

    - name: Start and enable k3s service
      service:
        name: k3s
        state: started
        enabled: yes
      when: k3s_install_result.changed
